### PR TITLE
Some minor improvements

### PR DESCRIPTION
**Pull request by manoedinata**

### CODE REVIEW

**Comment by oxraphc** [comment]
Yoo thanks a lot bro, i didn't expect a pull request. learned a new thing or two. but my question is, why?
I noticed that you switched the wikipedia source to Indonesian, I was originally preferring the English version for that ('cuz why not)

**Comment by oxraphc** [comment]
nvm, thanks a lot. appreciate it

**Comment by manoedinata** [comment]
> Yoo thanks a lot bro, i didn't expect a pull request. learned a new thing or two. but my question is, why? I noticed that you switched the wikipedia source to Indonesian, I was originally preferring the English version for that ('cuz why not)

The new Wikipedia page has a better data and we don't need to sanitize it. So, why not?

Besides, I hate regex, unless you have the absolute urge to use it, just switch to a better data if any.

**Comment by oxraphc** [comment]
Understandable. To be clear, I was challenging myself to use regex at some point, but I think your solution was more concise and simpler.

**Pull request merged**
